
name: Compilar ejecutable para Windows con Pyinstaller

on:
  push:
    branches: [ main , dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compilar aplicación
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
    - name: Subir artefacto
      uses: actions/upload-artifact@v3.1.0
      with:
        name: windows-build
        path: dist/Haze.exe
